[package]
name = "windusb-gui"
version = "1.0.0"
edition = "2021"

[dependencies]
libc = "0.2"
ctrlc = "3.4"
tempfile = "3.8"
glib = "0.18"
gtk4 = "0.7"

[dependencies.libadwaita]
version = "0.5"
features = ["v1_2"]
